name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: bootstrap
      run: ./bootstrap.sh
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure
    - name: uname
      run: uname -a
    - name: env
      run: cat /etc/os-release
    - name: make
      run: make -j `nproc`
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
